### ISSUE TITLE
До выхода СППР на 8.3.11 не рекомендовать использовать данное расширение.

### ISSUE THREAD

**Issue by zeegin** [JohnyDeath/GitterExtForSPPR#1]
> 2. Перевести базу 1С:СППР на совместимость с 8.3.11 и старше

И получить развал в любом произвольном месте, т.к. БСП 2.4.4 предназначена для работы с платформой 8.3.10. Надо подождать адаптации к платформе 8.3.11. В продакшине использовать не рекомендуется, только в режиме теста.

**Comment by JohnyDeath** [comment]
Так и есть.
Добавил в описание.
Спасибо.
